- name: Deploy Docker container
  hosts: localhost
  become: yes
  tasks:
    - name: Stop existing container
      shell: docker stop mywebapp || true && docker rm mywebapp || true

    - name: Run new container
      shell: docker run -d -p 8081:8080 --name mywebapp mywebapp:latest
